name: Replenish
version: 1.3.0
main: dev.replenish.ReplenishPlugin
api-version: '1.21'
author: Mitra
commands:
  replenish:
    description: Manage Replenish plugin (toggle/reload)
    usage: /replenish <toggle|reload>
permissions:
  replenish.toggle:
    description: Toggle plugin globally
    default: op
  replenish.reload:
    description: Reload config
    default: op
